Update edit-keyboard-mapping.component.ts
tv2/ng-sofie pull request #228
Opened 2024-07-02 10:39 UTC by aardhuis

Removed forgotten "debugger" symbol

2024-07-02 10:59 UTC, LindvedKrvang approved these changes

2024-07-02 11:27 UTC, RasmusAlbrektsen approved these changes

2024-07-02 11:29 UTC, MadsThy approved these changes

2024-07-03 06:38 UTC, RasmusAlbrektsen requested changes
I'm making a request for changes because my comments will ensure we don't fail linting on our automerge towards develop.

2024-07-03 06:38 UTC, RasmusAlbrektsen commented on src/app/settings/keyboard-mapping-settings/components/edit-keyboard-mapping/edit-keyboard-mapping.component.ts
Twice in this file you have used `var`, this is from the earlier PR and i didn't catch it there, this should be changed :-)

2024-07-03 06:43 UTC, aardhuis commented on src/app/settings/keyboard-mapping-settings/components/edit-keyboard-mapping/edit-keyboard-mapping.component.ts
I got a comment in slack about it, so since I thought this had been merged I made another PR called minor-refactor-hot-patch

2024-07-03 06:46 UTC, RasmusAlbrektsen commented on src/app/settings/keyboard-mapping-settings/components/edit-keyboard-mapping/edit-keyboard-mapping.component.ts
Oh okay. You still have the same issue on line 89 of the file as well. Just change that one to a const i think.

2024-07-03 06:46 UTC, RasmusAlbrektsen commented on src/app/settings/keyboard-mapping-settings/components/edit-keyboard-mapping/edit-keyboard-mapping.component.ts
I'll remove the request for changes here and assume it will be handled on the other PR.

2024-07-03 06:47 UTC, RasmusAlbrektsen approved these changes

2024-07-03 10:16 UTC, merged