SOF-1677 Standardize Yarn Scripts
tv2/ng-sofie pull request #79
Opened 2023-12-08 12:36 UTC by andr9528

Copied `clean` and `reset` script from Sofie Server repository.

Looking at the raw copied scripts, I removed the `*.log` from the reset, as the reset didn't appear to do anything if it that was there, and it failed to find any matching files. Has the `reset` been tested in Sofie Server?

2023-12-08 21:25 UTC, KvelaGorrrrnio requested changes
`*.log` removes files like `yarn-error.log`, which are not there by default, but if the developer makes a mistake or the build system encounters an error. So it will still be fine to keep :)

Currently the only scripts that adhere to the agreed standards are `build`, `lint`, `lint-fix`, `clean` and `reset`. The rest does not :)

2023-12-11 09:39 UTC, andr9528 commented
The `yarn reset` is split into two `rimraf` commands, as the `*.log` segment, makes the rimraf command only target the specific file type in the targeted folders. From my understanding, we want to nuke the folders AND all files with the `*.log` extension.

2023-12-14 09:07 UTC, KvelaGorrrrnio reviewed
Looks good :+1:

2023-12-14 09:07 UTC, KvelaGorrrrnio commented on package.json
It would be nice to have the `test-watch` and `build-watch` scripts available as well:
```json
{
  "scripts": {
    "build-watch": "ng build --watch --configuration production",
    "test-watch": "ng test",
  }
}
```

2023-12-14 09:08 UTC, KvelaGorrrrnio approved these changes

2024-01-10 08:13 UTC, LindvedKrvang approved these changes

2024-01-11 09:48 UTC, merged