SOF-1721 - Cycle MiniShelves back and forth
tv2/ng-sofie pull request #93
Opened 2024-01-25 06:52 UTC by k-primeholding-dim

RundownComponent to listen for keyboard events like:
- Tab - find the next VideoClipAction in the next Minishelf and insert it as Next. Continuesly pressing “Tab” will find the next VideoClipAction after that and insert it. The inserted Clip will have a green tally. A playing clip has a red tally.
- Shift-Tab (same as next)
- Alt-Tab - find the previous VideoClipAction and insert it.

2024-01-26 09:35 UTC, KvelaGorrrrnio commented
Since this is based on #88, it would be nice if the target branch is changed to `SOF-1720/display-minishelf` and a note in the PR description that it is based on another feature branch/ PR.

2024-01-26 10:45 UTC, k-primeholding-dim commented
This feature branch should reach develop once complete.

2024-01-29 06:55 UTC, LindvedKrvang commented
> This feature branch should reach develop once complete. My other option was to block till #88 is merged.

No need to block this task untill #88 is merged and no need to not target #88 from PR. This PR will still reach `develop`.

PRs that have been made from other branches should still target the branch they have been made from. If they don't and target develop, like here, we have no idea which changes is the changes relevant for this PR (which are changes that should be reveiwed in this PR), and which changes are for the target PR (which are changes that should not be reveiwed in this PR).

PRs that are targeting other PRs will have their target branch updated automatically when their target PR is merged. By not targeting the PR/branch this is branched from, you are "blocking" us from reviewing this PR untill the original branch/PR has been merged.

The important thing is that _this_ PR should _not_ be merged untill the target PR has been merged.

2024-02-01 09:05 UTC, LindvedKrvang requested changes
The request for changes is primarily because you have introduced a lot of static methods which goes against a lot of the principles that we are following

2024-02-01 09:05 UTC, LindvedKrvang commented on src/app/shared/services/action-state.service.ts
> +  }
This is just a "parse-through" method. 
You should just inject `ActionService` directly into the component that needs to execute the Action

2024-02-06 14:43 UTC, k-primeholding-dim commented
Closing this one, work continues in https://github.com/tv2/ng-sofie/pull/99

2024-02-06 14:43 UTC, closed without merging